### PR TITLE
test error corrected

### PR DESCRIPTION
**Pull request by yahyaKacem**
Correcting the karma test error: 'pascalprecht.paginator  should return paginator data object FAILED'
check the comments in the spec file.

### CODE REVIEW

**Comment by 0x-r4bbit** [comment]
Thanks though! Will dig into that one

**Comment by yahyaKacem** [comment]
OK, that's why I sent a pull request, to check with you about those changes, I'll try to keep your naming conventions for next pull request.  
I'll try to add a usage demo. maybe some documentation so it will be easier to implement it without reading the code.

**Comment by 0x-r4bbit** [comment]
Basically, demos are cool, but the code isn't ready yet at all. So I think we should focus on making angular-paginator functional. How about just updating thing PR? Simply push to your canary and this PR gets updated. Once that spacing thing is cleaned up, I think I can merge it in :) After that we can talk about behavior stuff write more tests :)

**Comment by yahyaKacem** [comment]
About the demo I didn't mean a demo for users but for me so I can better understand the functionality of the code.
for example i made a test now to check that perPage is equal to 10, and I want to make a second one where I set the perPage in the test function to 25 and check if it changed, but I didn't know how to assign 25 to perPage in the test function.

**Comment by 0x-r4bbit** [comment]
Okay, thanks for updating the PR, I'll merge it in for now :)

**Comment by 0x-r4bbit** [comment]
@yahyaKacem Hey, I'll update the tests with proper async expects and show you how it works. The reason for this is that each `expect()` within an async `then()` will be true, because its not evaluated in the right scope.

In short:

```
it('foo', function () {
  inject(function (bar) {
    bar().then(function () {
       expect(true).toBe(false);
    });
  });
});
```

Will pass. Which is not true.

**Comment by 0x-r4bbit** [comment]
Here's a commit which shows proper testing for async apis :) https://github.com/PascalPrecht/angular-paginator/commit/059ca1b0d6bda00287b718ec688cb2bee9399ca0

**Pull request merged**
